"""Add role column to human_agents table

Revision ID: 4bf8c2a7d7c6
Revises: 
Create Date: 2025-10-22 20:22:17.307380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf8c2a7d7c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human_agents', sa.Column('role', sa.Enum('ADMIN', 'AGENT', name='agentrole'), server_default='AGENT', nullable=False))

    # Set the first agent as admin
    op.execute("""
        UPDATE human_agents
        SET role = 'ADMIN'
        WHERE id = (SELECT MIN(id) FROM human_agents)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('human_agents', 'role')
    # ### end Alembic commands ###
